apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
type: Opaque
stringData:
  TELEGRAM_TOKEN: {{ .Values.telegram.token | quote }}
  TELEGRAM_CHAT_ID: {{ .Values.telegram.chat_id | quote }}
  GEMINI_API_KEY: {{ .Values.gemini.api_key | quote }}
